"""
app/models/projection.py
========================
DocumentProjection, EvidenceListProjection, FileRenamePlan

These are PROJECTIONS — computed views of the canonical state.
They are regenerated on each render-preview call and on commit.
They are NOT the source of truth.

DDL mapping
-----------
document_projections
  PK         : id  SERIAL
  Indexes    : ix_document_projections_document_id
               ix_document_projections_change_set_id
               ix_doc_proj_doc_cs  (document_id, change_set_id) composite
  FK out     : document_id  → documents.id   ON DELETE CASCADE
               change_set_id → change_sets.id ON DELETE CASCADE

evidence_list_projections
  PK         : id  SERIAL
  Indexes    : ix_evidence_list_projections_evidence_id
               ix_evidence_list_projections_change_set_id
               ix_evp_ev_cs  (evidence_id, change_set_id) composite
  FK out     : evidence_id  → evidences.id   ON DELETE CASCADE
               change_set_id → change_sets.id ON DELETE CASCADE

file_rename_plans
  PK         : id  SERIAL
  Indexes    : ix_file_rename_plans_source_file_id
               ix_file_rename_plans_change_set_id
               ix_frp_status  (status)
  FK out     : source_file_id → source_files.id ON DELETE CASCADE
               change_set_id  → change_sets.id   ON DELETE CASCADE

Status column
-------------
FileRenamePlan.status → FileRenamePlanStatus enum  VARCHAR(50)
"""

from datetime import datetime
from sqlalchemy import (
    String, Integer, ForeignKey, DateTime, Index,
    Text, JSON, func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base
from app.models.enums import FileRenamePlanStatus


class DocumentProjection(Base):
    """Rendered preview of a document body with evidence numbers substituted.

    Generated by the document renderer; stored here so the preview can be
    compared across render calls (content_hash detects unchanged renders).

    NOT the source of truth — regenerated on demand.
    The canonical data lives in Document + DocumentAnchor + Reference + Evidence.
    """

    __tablename__ = "document_projections"

    # ── Primary key ──────────────────────────────────────────────────────────
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    # ── Foreign keys ─────────────────────────────────────────────────────────
    document_id: Mapped[int] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"),
        nullable=False,
    )
    # NULL → baseline render (no pending ChangeSet); non-NULL → preview for a ChangeSet
    change_set_id: Mapped[int | None] = mapped_column(
        ForeignKey("change_sets.id", ondelete="CASCADE"),
        nullable=True,
        comment="NULL = committed/baseline render; non-NULL = preview for given ChangeSet",
    )

    # ── Rendered content ─────────────────────────────────────────────────────
    # Paragraph list as JSON: [{"index": 0, "text": "...", "placeholders": [...]}]
    rendered_content: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=dict,
        comment="Full rendered paragraph list; format defined by DocumentRenderer",
    )
    # SHA-256 of the rendered content for quick change detection
    content_hash: Mapped[str | None] = mapped_column(
        String(64),
        nullable=True,
        comment="SHA-256 of rendered_content JSON; used to detect unchanged re-renders",
    )

    # ── Timestamps ───────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=False), server_default=func.now(), nullable=False
    )

    # ── Table-level constraints & indexes ────────────────────────────────────
    __table_args__ = (
        Index("ix_document_projections_document_id", "document_id"),
        Index("ix_document_projections_change_set_id", "change_set_id"),
        # Composite: quickly find latest projection for (document, change_set) pair
        Index("ix_doc_proj_doc_cs", "document_id", "change_set_id"),
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    document: Mapped["Document"] = relationship(  # noqa: F821
        "Document",
        back_populates="projections",
    )
    change_set: Mapped["ChangeSet | None"] = relationship(  # noqa: F821
        "ChangeSet",
        back_populates="document_projections",
    )

    def __repr__(self) -> str:
        return (
            f"<DocumentProjection id={self.id} "
            f"doc={self.document_id} cs={self.change_set_id}>"
        )


class EvidenceListProjection(Base):
    """Rendered preview of an evidence list entry.

    Generated by the evidence list renderer from (Evidence.party, Evidence.sort_order).
    ``rendered_number`` is the formatted string (e.g. '갑 제1호증').

    NOT the source of truth — the canonical number is computed on demand from
    (party, sort_order).
    """

    __tablename__ = "evidence_list_projections"

    # ── Primary key ──────────────────────────────────────────────────────────
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    # ── Foreign keys ─────────────────────────────────────────────────────────
    evidence_id: Mapped[int] = mapped_column(
        ForeignKey("evidences.id", ondelete="CASCADE"),
        nullable=False,
    )
    change_set_id: Mapped[int | None] = mapped_column(
        ForeignKey("change_sets.id", ondelete="CASCADE"),
        nullable=True,
        comment="NULL = committed/baseline render; non-NULL = preview for given ChangeSet",
    )

    # ── Rendered fields ───────────────────────────────────────────────────────
    # Snapshot of the rendered number at projection time (e.g. '갑 제1호증')
    rendered_number: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="Formatted evidence number at projection time (e.g. '갑 제1호증')",
    )
    rendered_label: Mapped[str] = mapped_column(
        String(512),
        nullable=False,
        comment="Evidence label snapshot at projection time",
    )
    rendered_description: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Snapshot of sort_order at projection time (for diff / history)
    sort_order_snapshot: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Evidence.sort_order value captured when this projection was created",
    )

    # ── Timestamps ───────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=False), server_default=func.now(), nullable=False
    )

    # ── Table-level constraints & indexes ────────────────────────────────────
    __table_args__ = (
        Index("ix_evidence_list_projections_evidence_id", "evidence_id"),
        Index("ix_evidence_list_projections_change_set_id", "change_set_id"),
        # Composite: latest projection for (evidence, change_set)
        Index("ix_evp_ev_cs", "evidence_id", "change_set_id"),
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    evidence: Mapped["Evidence"] = relationship(  # noqa: F821
        "Evidence",
        back_populates="evidence_list_projections",
    )
    change_set: Mapped["ChangeSet | None"] = relationship(  # noqa: F821
        "ChangeSet",
        back_populates="evidence_list_projections",
    )

    def __repr__(self) -> str:
        return (
            f"<EvidenceListProjection id={self.id} "
            f"number={self.rendered_number!r} evidence={self.evidence_id}>"
        )


class FileRenamePlan(Base):
    """A queued intent to rename a file on disk.

    The physical rename happens ONLY at ChangeSet commit time.
    Before commit, the disk filename is unchanged (``stored_filename`` stays put).

    Status
    ------
    FileRenamePlanStatus: planned | committed | reverted

    Lifecycle
    ---------
    1. Created with status=planned when a rename_file operation is added.
    2. At commit: file is physically renamed → status = committed.
    3. If rollback: status = reverted (and optionally a new plan restores original name).

    NOT a projection in the strict sense — it is a plan record that triggers
    a real side-effect (disk rename) at commit time.
    """

    __tablename__ = "file_rename_plans"

    # ── Primary key ──────────────────────────────────────────────────────────
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    # ── Foreign keys ─────────────────────────────────────────────────────────
    source_file_id: Mapped[int] = mapped_column(
        ForeignKey("source_files.id", ondelete="CASCADE"),
        nullable=False,
    )
    change_set_id: Mapped[int | None] = mapped_column(
        ForeignKey("change_sets.id", ondelete="CASCADE"),
        nullable=True,
        comment="The ChangeSet that produced this rename plan",
    )

    # ── Rename intent ─────────────────────────────────────────────────────────
    current_filename: Mapped[str] = mapped_column(
        String(512),
        nullable=False,
        comment="Filename on disk BEFORE the rename (matches stored_filename at plan time)",
    )
    planned_filename: Mapped[str] = mapped_column(
        String(512),
        nullable=False,
        comment="Target filename AFTER the rename (e.g. '갑 제1호증 계약서.docx')",
    )

    # ── Status ───────────────────────────────────────────────────────────────
    # FileRenamePlanStatus: planned | committed | reverted
    status: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default=FileRenamePlanStatus.PLANNED.value,
        server_default=FileRenamePlanStatus.PLANNED.value,
        comment="FileRenamePlanStatus: planned | committed | reverted",
    )

    # ── Timestamps ───────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=False), server_default=func.now(), nullable=False
    )
    committed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=False),
        nullable=True,
        comment="Set when physical rename completes",
    )

    # ── Table-level constraints & indexes ────────────────────────────────────
    __table_args__ = (
        Index("ix_file_rename_plans_source_file_id", "source_file_id"),
        Index("ix_file_rename_plans_change_set_id", "change_set_id"),
        Index("ix_frp_status", "status"),
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    source_file: Mapped["SourceFile"] = relationship(  # noqa: F821
        "SourceFile",
        back_populates="file_rename_plans",
    )
    change_set: Mapped["ChangeSet | None"] = relationship(  # noqa: F821
        "ChangeSet",
        back_populates="file_rename_plans",
    )

    # ── Helpers ───────────────────────────────────────────────────────────────
    @property
    def is_pending(self) -> bool:
        return self.status == FileRenamePlanStatus.PLANNED.value

    def __repr__(self) -> str:
        return (
            f"<FileRenamePlan id={self.id} "
            f"{self.current_filename!r} → {self.planned_filename!r} "
            f"status={self.status}>"
        )
